### ISSUE TITLE
New device: DIN rail energy meter with relay and leakage detection

### ISSUE THREAD

**Issue by fakuivan** [tuya-cloudcutter/tuya-cloudcutter.github.io#72]
This thing goes by a few names, the model I got comes with a WB3S module, UART1 is connected to the main MCU, they communicate using the Tuya MCU protocol.

Here are some similar models:
* [Aliexpress: tuya smart life wifi Smart Energy Meter Power kWh Meter Earth Leakage Over Under Voltage Protector work with alexa smart home](https://aliexpress.com/item/1005005267060627.html)
* [Aliexpress: 2P 63A TUYA APP WiFi Smart Circuit Earth Leakage Over Under Voltage Protector Relay Device Switch Breaker Energy Power kWh Meter](https://www.aliexpress.com/item/1005005813908844.html)
* [Aliexpress: Tuya Din Rail WIFI Smart Energy Meter 60A 63A Timer Power Consumption Kwh Meter Wattmeter Single Phase Support Smartlife App](https://www.aliexpress.com/item/1005004397726424.html)
* [Aliexpress: 2P 63A TUYA APP Din Rail WiFi Smart Circuit Earth Leakage Over Under Voltage Protector Relay Device Switch Power kWh Meter](https://www.aliexpress.com/item/1005004563864260.html)

## Data on the tuya chip

```json
{
    "gw_bi": {
        "uuid": "7bfe30995b5ed073",
        "psk_key": "4dzxbgkIXItQmebisEO3sCi3IXlYIqaCtfPGw",
        "auth_key": "dNERmpv2u8p2kCC7WW2U9Hf5x6nWU3G3",
        "ap_ssid": "SmartLife",
        "ap_passwd": null,
        "country_code": "CN",
        "bt_mac": null,
        "bt_hid": null,
        "prod_test": false
    },
    "baud_cfg": {
        "baud": 9600
    },
    "gw_wsm": {
        "nc_tp": 1,
        "ssid": null,
        "passwd": null,
        "md": 0,
        "random": 0,
        "wfb64": 1,
        "stat": 1,
        "token": null,
        "region": null,
        "reg_key": null,
        "dns_prio": 0
    },
    "gw_di": {
        "abi": 0,
        "id": "6c7292f508c72a4e3cj3er",
        "swv": "1.1.80",
        "bv": "40.00",
        "pv": "2.2",
        "lpv": "3.3",
        "pk": "wcihaluccfsoayqa",
        "firmk": "key34ak4q5rmrkef",
        "cadv": "1.0.2",
        "cdv": "1.0.0",
        "dev_swv": "1.0.0",
        "s_id": "000004pxun",
        "dtp": 1,
        "sync": 0,
        "attr_num": 0,
        "mst_tp_0": 0,
        "mst_ver_0": null,
        "mst_tp_1": 0,
        "mst_ver_1": null,
        "mst_tp_2": 0,
        "mst_ver_2": null,
        "mst_tp_3": 0,
        "mst_ver_3": null,
        "dminfo_name": null,
        "dminfo_code": null,
        "dminfo_report_code": null,
        "dminfo_sn": null
    },
    "gw_ai": {
        "key": "c9e2a4fa284eb63b",
        "lckey": "f8f74f0cdd292dd0",
        "h_url": "http://a.tuyacn.com/d.json",
        "h_ip": "42.192.25.216",
        "hs_url": null,
        "hs_ip": null,
        "hs_psk": "https://a3.tuyacn.com/d.json",
        "hs_psk_ip": "121.5.96.248",
        "mqs_url": null,
        "mqs_ip": null,
        "mq_url": "m2.tuyacn.com:1883",
        "mq_ip": "42.192.31.85",
        "ai_sp": null,
        "mq_psk": "m2.tuyacn.com:8886",
        "mq_psk_ip": "42.192.31.85",
        "time_z": "+08:00",
        "s_time_z": "[]",
        "wx_app_id": null,
        "wx_uuid": null,
        "dy_tls_m": 0,
        "cloud_cap": 1025
    },
    "is_stride": 0,
    "tls_ca_cnt": 0,
    "000004pxun": [
        {
            "type": "obj",
            "mode": "ro",
            "property": {
                "min": 0,
                "max": 99999999,
                "scale": 2,
                "step": 1,
                "type": "value"
            },
            "id": 1
        },
        {
            "mode": "ro",
            "id": 6,
            "type": "raw"
        },
        {
            "type": "obj",
            "mode": "ro",
            "property": {
                "type": "bitmap",
                "maxlen": 17
            },
            "id": 9
        },
        {
            "type": "obj",
            "mode": "rw",
            "property": {
                "type": "bool"
            },
            "id": 11
        },
        {
            "type": "obj",
            "mode": "rw",
            "property": {
                "type": "bool"
            },
            "id": 12
        },
        {
            "type": "obj",
            "mode": "ro",
            "property": {
                "min": 0,
                "max": 99999999,
                "scale": 2,
                "step": 1,
                "type": "value"
            },
            "id": 13
        },
        {
            "type": "obj",
            "mode": "rw",
            "property": {
                "min": 0,
                "max": 999999,
                "scale": 2,
                "step": 1,
                "type": "value"
            },
            "id": 14
        },
        {
            "type": "obj",
            "mode": "ro",
            "property": {
                "min": 0,
                "max": 1000,
                "scale": 0,
                "step": 1,
                "type": "value"
            },
            "id": 15
        },
        {
            "type": "obj",
            "mode": "rw",
            "property": {
                "type": "bool"
            },
            "id": 16
        },
        {
            "mode": "rw",
            "id": 17,
            "type": "raw"
        },
        {
            "mode": "rw",
            "id": 18,
            "type": "raw"
        },
        {
            "type": "obj",
            "mode": "ro",
            "property": {
                "type": "string",
                "maxlen": 255
            },
            "id": 19
        },
        {
            "type": "obj",
            "mode": "rw",
            "property": {
                "min": 1,
                "max": 30,
                "scale": 0,
                "step": 1,
                "type": "value"
            },
            "id": 104
        },
        {
            "type": "obj",
            "mode": "rw",
            "property": {
                "min": 1,
                "max": 500,
                "scale": 0,
                "step": 1,
                "type": "value"
            },
            "id": 105
        }
    ],
    "em_sys_env": "BK7231S_2M",
    "timer_arr": {
        "lastFetchTime": 0,
        "cnt": 0
    }
}
```

### Firmware dump:

[ltchiptool_bk72xx_2023-08-18_10-59-12.zip](https://github.com/tuya-cloudcutter/tuya-cloudcutter.github.io/files/12411490/ltchiptool_bk72xx_2023-08-18_10-59-12.zip)

## Example config

I made this config file that uses some of the available datapoints.

```yaml
esphome:
  name: smart-power-meter
  friendly_name: smart_power_meter

substitutions:
  dp_clear: "12"

bk72xx:
  board: wb3s
  framework:
    version: dev

# Enable Tuya MCU
uart:
  tx_pin: TX1
  rx_pin: RX1
  baud_rate: 9600

tuya:
  id: tuya_mcu
  on_datapoint_update:
  - sensor_datapoint: 6
    datapoint_type: raw
    then:
    - lambda: |-
        const float voltage = (x[0] << 8 | x[1]) * 0.1;
        const float curr = (x[3] << 8 | x[4]) * 0.001;
        const float active_power = (x[6] << 8 | x[7]);
        const float ap_power = voltage*curr;
        id(vin_rms).publish_state(voltage);
        id(current).publish_state(curr);
        id(power).publish_state(active_power);
        id(apparent_power).publish_state(ap_power);
        // In rare cases active power > apparent power, meaning that active power is
        // not measured in the same way as current or voltage.
        id(power_factor).publish_state(ap_power != 0. ? active_power/ap_power : 0.);
  - sensor_datapoint: $dp_clear
    datapoint_type: bool
    then:
    - lambda: |-
        if (x)
          id(tuya_mcu).set_boolean_datapoint_value($dp_clear, false);

switch:
  - platform: "tuya"
    name: "Output relay"
    switch_datapoint: 16
  - platform: tuya
    name: Datapoint 11
    switch_datapoint: 11

button:
- platform: template
  name: Clear energy usage
  on_press:
    then:
      lambda: |-
        id(tuya_mcu).set_boolean_datapoint_value($dp_clear, true);


sensor:
  - platform: "tuya"
    name: "Total power consumption"
    sensor_datapoint: 1
    state_class: total_increasing
    device_class: energy
    unit_of_measurement: kWh
    accuracy_decimals: 1
    filters:
    - multiply: 0.01

  - platform: "tuya"
    name: "Leakage current"
    sensor_datapoint: 15
    state_class: measurement
    device_class: current
    unit_of_measurement: mA
    accuracy_decimals: 0

  - name: "Input Voltage"
    platform: template
    id: vin_rms
    state_class: measurement
    device_class: voltage
    unit_of_measurement: V
    accuracy_decimals: 0

  - name: "Active power"
    platform: template
    id: power
    state_class: measurement
    device_class: power
    unit_of_measurement: W
    accuracy_decimals: 0

  - name: "Apparent power"
    platform: template
    id: apparent_power
    state_class: measurement
    device_class: apparent_power
    unit_of_measurement: VA
    accuracy_decimals: 2

  - name: "Power factor"
    platform: template
    id: power_factor
    state_class: measurement
    device_class: power_factor
    accuracy_decimals: 2

  - platform: "template"
    name: "Output current"
    id: current
    state_class: measurement
    device_class: current
    unit_of_measurement: A
    accuracy_decimals: 2

# Enable logging, uart 2 is not connected to anything, safe to log from there.
logger:

ota:
```

## What to do with the missing datapoints

Having configs be packet into bytes complicates things. Because of the way Tuya MCU works we can't changethe state of some bytes without also changing the other bytes in the same datapoint. To solve this we couldstart with a global where the latest state of the config datapoint is saved, this global can be modifiedby different Number entires and then pushed as raw to the MCU. The inherent problem with shared mutablestate is that we'll need some sort of lock to avoid concurrent writes. A simpler approach would be to writeall changes to the global and then send that state when an update is received from the MCU.

All this gets complicated if the MCU can change the configs itself, for now we'll assume that the state can only be changed through esphome chip.

It'd be a good idea to look for other configs where this happens and maybe use that as an example of how to solve it.

As for serializing and deserializing the raw entries, here's an example struct to store and read configs, can get messed up with different endianness since we're stuffing bytes into structs directly, but it's simpler to write this way. This struct corresponds to datapoint 18.

```cpp
#include <algorithm>
#include <vector>

union main_config {
    uint8_t bits[20];
    struct {
        uint8_t unknown5[4];
        uint16_t max_leak_current;
        uint8_t unknown4[2];
        uint16_t min_voltage;
        uint8_t unknown3[2];
        uint16_t max_voltage;
        uint8_t unknown2[2];
        uint16_t max_current;
        uint8_t unknown[2];
    } fields;
    main_config(const std::vector<uint8_t> &raw) {
        std::reverse_copy(raw.begin(), raw.end(), bits);
    }
    std::vector<uint8_t> to_raw() const {
        std::vector<uint8_t> raw(sizeof bits);
        std::reverse_copy(std::begin(bits), std::end(bits), raw.begin());
        return raw;
    }
};
```

If you need to stop the relay from disconnecting because of current leakage asap, use these buttons, they set max leakage to
90mA. In videos I've seen about this product they show a toggle to disable individual protections, so there must be a bit somewhere
we can reverse and bypass this entirely.

```yaml
button:
# Sets max leakage current to 90mA, for testing purposes
- platform: template
  name: Fix leak
  on_press:
    then:
      lambda: |-
        id(tuya_mcu).set_raw_datapoint_value(18, {1, 1, 0, 63, 3, 1, 1, 14, 4, 1, 0, 170, 8, 0, 0, 90, 9, 0, 0, 0});
        id(tuya_mcu).set_raw_datapoint_value(17, {4, 1, 0, 90});
# Sets max leakage current back to 30mA, for testing purposes
- platform: template
  name: Create leak
  on_press:
    then:
      lambda: |-
        id(tuya_mcu).set_raw_datapoint_value(18, {1, 1, 0, 63, 3, 1, 1, 14, 4, 1, 0, 170, 8, 0, 0, 30, 9, 0, 0, 0});
        id(tuya_mcu).set_raw_datapoint_value(17, {4, 1, 0, 30});
```
